services:
  janusstreaming:
    build: .
    volumes:
      - /home/letsencrypt:/etc/letsencrypt
      - /home/robert/janusStreaming/configs:/opt/janus/etc/janus
    tty: true
    network_mode: "host"
    restart: always
